<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="EPBYGOMW0114" ignored="0" name="Test Double Division by Zero" tests="5" failures="1" timestamp="23 Apr 2018 14:02:31 GMT" time="0.024" errors="0">
  <testcase name="divDoubleTestException" time="0.0" classname="com.epam.mentoring.globoforce.calculator.test.DivDoubleTest">
    <failure type="org.testng.TestException" message="
Method DivDoubleTest.divDoubleTestException(double, double)[pri:0, instance:com.epam.mentoring.globoforce.calculator.test.DivDoubleTest@24273305] should have thrown an exception of type class java.lang.ArithmeticException">
      <![CDATA[org.testng.TestException: 
Method DivDoubleTest.divDoubleTestException(double, double)[pri:0, instance:com.epam.mentoring.globoforce.calculator.test.DivDoubleTest@24273305] should have thrown an exception of type class java.lang.ArithmeticException
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
... Removed 7 stack frames]]>
    </failure>
  </testcase> <!-- divDoubleTestException -->
  <testcase name="divLongTest" time="0.001" classname="com.epam.mentoring.globoforce.calculator.test.DivDoubleTest"/>
  <testcase name="divLongTest" time="0.0" classname="com.epam.mentoring.globoforce.calculator.test.DivDoubleTest"/>
  <testcase name="divLongTest" time="0.0" classname="com.epam.mentoring.globoforce.calculator.test.DivDoubleTest"/>
  <testcase name="divLongTest" time="0.0" classname="com.epam.mentoring.globoforce.calculator.test.DivDoubleTest"/>
</testsuite> <!-- Test Double Division by Zero -->
